name: Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APP_SERVICE_NAME: 'webapp-12factorapp-240603' # Azure Web Appsのリソース名を入れてください
  ACCOUNT_NAME: 'ykiyoshima' # GitHubのアカウント名を入れてください

jobs:
  # .NET6 Webアプリのビルド
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './TFApp_before'

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      # プロジェクトビルド時にパッケージリストアする必要があるため、NuGetソースにGitHub Packagesを追加します
      - name: Nuget add source for GitHub Packages
        run: dotnet nuget add source --username ${{ env.ACCOUNT_NAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ env.ACCOUNT_NAME }}/index.json"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  # AzureWeb Appsへのデプロイ
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          package: .